"use client"

import { motion } from "framer-motion"

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-[#e8e4df] to-[#f5f2ee]">
      <div className="container mx-auto px-6 py-12">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="max-w-3xl mx-auto bg-card rounded-3xl shadow-xl p-8 md:p-12"
        >
          <div className="text-center mb-12 pb-8 border-b border-border/30">
            <a href="/" className="inline-flex items-center gap-2 mb-8 group">
              <div className="w-8 h-8 bg-primary rounded-md flex items-center justify-center">
                <span className="text-primary-foreground font-bold text-lg">L</span>
              </div>
              <span className="font-bold text-xl text-foreground group-hover:text-primary transition-colors">
                LEVITATE
              </span>
            </a>
          </div>

          <h1 className="text-4xl md:text-5xl font-bold text-center mb-2 text-foreground">Terms of Service</h1>
          <p className="text-center text-muted-foreground text-sm mb-12">Last Updated: January 30, 2026</p>

          <div className="space-y-8 text-foreground/80">
            <p className="leading-relaxed">
              By downloading or using Levitate ("the App"), you agree to the following terms and conditions.
            </p>

            <div>
              <h2 className="text-xl font-bold mb-4 text-foreground uppercase tracking-wide">
                1. Description of Service
              </h2>
              <p className="leading-relaxed">
                Levitate is a generative AI tool designed for meditation, focus, and relaxation. The App uses artificial intelligence to create personalized meditation scripts and delivers them through AI-generated voice synthesis.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold mb-4 text-foreground uppercase tracking-wide">
                2. AI-Generated Content Disclaimer
              </h2>
              <p className="mb-3 leading-relaxed">
                <strong>All meditation content in Levitate is generated by artificial intelligence.</strong> By using the App, you acknowledge and agree that:
              </p>
              <ul className="list-disc list-inside space-y-2 pl-4 leading-relaxed">
                <li>Content is created in real-time by AI models and may occasionally be imperfect, unexpected, or unsuitable for your specific needs.</li>
                <li>Levitate is <strong>not a medical device</strong> and is <strong>not a substitute</strong> for professional mental health therapy, counseling, or medical advice.</li>
                <li>The App should not be used during mental health emergencies. If you are experiencing a crisis, please contact a mental health professional or emergency services immediately.</li>
                <li>We do not guarantee that AI-generated content will be accurate, appropriate, or beneficial for every user.</li>
              </ul>
            </div>

            <div>
              <h2 className="text-xl font-bold mb-4 text-foreground uppercase tracking-wide">
                3. Health & Wellness Disclaimer
              </h2>
              <p className="leading-relaxed">
                Levitate is intended for general wellness purposes only. It is not designed to diagnose, treat, cure, or prevent any disease or health condition. Always consult with a qualified healthcare provider before beginning any meditation practice, especially if you have a history of mental health conditions, trauma, or other health concerns.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold mb-4 text-foreground uppercase tracking-wide">4. Subscriptions & Payments</h2>
              <p className="mb-3 leading-relaxed">
                Levitate provides access to premium features via auto-renewing subscriptions managed through Apple's App Store.
              </p>
              <ul className="list-disc list-inside space-y-2 pl-4 leading-relaxed">
                <li>Payment will be charged to your Apple ID account at the confirmation of purchase.</li>
                <li>
                  Subscription automatically renews unless it is canceled at least 24 hours before the end of the
                  current period.
                </li>
                <li>
                  Your account will be charged for renewal within 24 hours prior to the end of the current period.
                </li>
                <li>
                  You can manage and cancel your subscriptions by going to your App Store account settings after
                  purchase.
                </li>
                <li>
                  <strong>Refunds:</strong> All purchases are processed through Apple. Refund requests must be submitted directly to Apple through their standard refund process.
                </li>
              </ul>
            </div>

            <div>
              <h2 className="text-xl font-bold mb-4 text-foreground uppercase tracking-wide">
                5. Content Ownership
              </h2>
              <p className="leading-relaxed">
                The visual interfaces, graphics, design, compilation, information, and computer code are the property of Levitate. AI-generated meditation content is created for your personal, non-commercial use only. You may not redistribute, resell, or commercially exploit generated content. You retain ownership of any personal reflections or journal entries you create within the App.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold mb-4 text-foreground uppercase tracking-wide">6. User Conduct</h2>
              <p className="leading-relaxed">
                You agree not to misuse the App or help anyone else to do so. This includes attempting to reverse engineer, hack, or circumvent security measures. Accessing the App through authorized means is the only allowed usage.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold mb-4 text-foreground uppercase tracking-wide">7. Limitation of Liability</h2>
              <p className="leading-relaxed">
                To the maximum extent permitted by law, Levitate and its creators shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the App. Your use of the App is at your own risk.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold mb-4 text-foreground uppercase tracking-wide">8. Termination</h2>
              <p className="leading-relaxed">
                We reserve the right to suspend or terminate your access to the Service at any time, for any reason,
                including if we reasonably believe you have violated these Terms.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold mb-4 text-foreground uppercase tracking-wide">9. Changes to Terms</h2>
              <p className="leading-relaxed">
                We may update these Terms from time to time. Continued use of the App after changes constitutes acceptance of the new Terms. We encourage you to review these Terms periodically.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold mb-4 text-foreground uppercase tracking-wide">10. Contact</h2>
              <p className="leading-relaxed">
                If you have any questions regarding these terms, please contact us at{" "}
                <a href="mailto:jiggsdwabber@gmail.com" className="text-primary font-semibold hover:underline">
                  jiggsdwabber@gmail.com
                </a>
                .
              </p>
            </div>
          </div>

          <div className="mt-16 pt-8 border-t border-border/30 text-center">
            <div className="flex items-center justify-center gap-6 text-sm mb-4">
              <a href="/support" className="text-muted-foreground hover:text-primary transition-colors">
                Support
              </a>
              <span className="text-muted-foreground">•</span>
              <a href="/privacy" className="text-muted-foreground hover:text-primary transition-colors">
                Privacy Policy
              </a>
            </div>
            <p className="text-muted-foreground text-sm">© 2026 Levitate</p>
          </div>
        </motion.div>
      </div>
    </div>
  )
}
